### ISSUE TITLE
Remove wildcard resx include?

### ISSUE THREAD

**Issue by mbp** [hvanbakel/CsprojToVs2017#10]
Any converted project file, whether it contains embedded resource files or not, will contain the lines:

```
  <ItemGroup>
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>
```

Why is it needed? Maybe we can make some conditional check for whether or not it needs to be there?

**Comment by hvanbakel** [comment]
So I got that from [here](vhttp://www.natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/). However it seems like VS now assumes these includes, the same for the cs files which I have already removed from being an inlcude. Let me verify that this is not needed.
