### ISSUE TITLE
Don't convert DefineConstants?

### ISSUE THREAD

**Issue by mbp** [hvanbakel/CsprojToVs2017#11]
Right now the project is looking for the first match of `DefineConstants` and using that value.

In reality however, in old csproj files there are multiple variants for each build configuration, e.g.:

```
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
```

In new project file format, these values are already default values (need not be specified) when you build with Debug and Release respectively.

But current logic will make us set `DEBUG` even for Release builds! 

I propose we just remove `DefineConstants` conversion.
Alternatively we should convert all of the build configuration specific properties.

**Comment by hvanbakel** [comment]
I don't think not converting `DefineConstants` is an option. There are valid cases where those are actually expanded upon that need to be ported over. What we could do however is to drop a constant like DEBUG if VS2017 assumes that based on your configuration.

**Comment by mbp** [comment]
Yes I do understand that someone might have important behavior based on these constants. But taking the first appearance, seems kinda arbitrary. So actually in this situation it might be better to copy the entire `<PropertyGroup>` sections including "Condition".

This will also then affect all other properties such as e.g. `OutputPath` which is by default `bin\Debug` but in new project format is actually `bin\Debug\xxx`  where xxx is e.g. net462.

**Comment by hvanbakel** [comment]
I actually removed the code yesterday to include those. When I did, Visual Studio started to ask if I wanted to install the WPF workload. That's why I didn't copy them.

This is an issue though as I have a problem with `<TreatWarningsAsErrors>` being on in Release, but not in DEV. That is now dropped.

**Comment by mbp** [comment]
After the fix, DefineConstants is now both defined in the first `<PropertyGroup>` section *and* in the conditional one.

**Comment by hvanbakel** [comment]
Let me verify, I converted a number of test projects yesterday without problems.
