### ISSUE TITLE
Removal of default assembly references should be moved from writer to a transform

### ISSUE THREAD

**Issue by mungojam** [hvanbakel/CsprojToVs2017#116]
This would then prevent an empty ItemGroup being written out when only default references were included

**Comment by cwuethrich** [comment]
I don't agree with this, the reference still belong to the Project. Its easier to prevent the empty ItemGroup in the output.

**Comment by mungojam** [comment]
You can probably still prevent empty outputs in the writer or as another transform

**Comment by cwuethrich** [comment]
It should be prevented now: https://github.com/hvanbakel/CsprojToVs2017/pull/133/commits/977ffbd3234758b079f48ae3314f3705d9ecb1b6

Yes I did a rollback. I think this one has do be implemented in the writer. I don't know if they are all the same for every FrameworkTarget. And what is with References like System.Data.DataSetExtension? This should be a reference in net46, but should be a package reference in netstandard2.0. So it could be in a posttransform. But also then, what if you have multi target projects, so you have to handle it for every target different and should use conditions...

**Comment by mungojam** [comment]
So for me all those complications are good reasons to have it as a transform, just one near the end of the list (doesn't need to be a post one). 

Unfortunately I have no idea on what is needed for which framework, that might be where the buildextrassdk package could help instead or something

**Comment by cwuethrich** [comment]
Yes, a transform at the end would be ok for projects with just one TargetFramework.
