### ISSUE TITLE
Consider adding support for other project formats by using MsBuildExtras

### ISSUE THREAD

**Issue by mungojam** [hvanbakel/CsprojToVs2017#126]
I've successfully converted a couple of WPF projects by making use of https://github.com/onovotny/MSBuildSdkExtras which leaves me with a really nice tidy project file that debugs fine.

They aren't natively supported by the converter, so I had to first delete all the GUIDs to trick it and then override the SDK and delete a load of items from the project file afterwards, e.g. XAML and XAML.cs files.

I guess I could do it with the new custom transforms by removing these specific GUIDs beforehand and then overriding the SDK afterwards (probably not supported by `ProjectDefinition` at the moment but could be added.

Maybe that could be added as an option since you may not want to assume that people are happy with a third party SDK in their resultant projects. Hopefully Microsoft's own SDK will work for these projects in the next VS!

**Comment by MagicAndre1981** [comment]
Does this "extra SDK" support WinForms? I noticed after converting the csproj that the property page of the WinForms solution is very limited and misses options like Remote Debug.

**Comment by mungojam** [comment]
I think so, at least in the latest preview. I've asked them to clarify in the docs https://github.com/onovotny/MSBuildSdkExtras/issues/87

**Comment by MagicAndre1981** [comment]
ok, I'll try this Extra thing and see how it works

**Comment by MagicAndre1981** [comment]
doesn't work for WinForms. Also the[ provided Sample](https://github.com/onovotny/MSBuildSdkExtras/tree/master/TestProjects/Windows-Desktop-C%23/WinForms-Application) is not working differently , it has the same issues as the SDK from Microsoft

**Comment by mungojam** [comment]
@MagicAndre1981 have you seen the mention on the readme that you have to add `<ExtrasEnableWinFormsProjectSetup>true</ExtrasEnableWinFormsProjectSetup>` for winforms? I think maybe that is just with the new version, but maybe only the new version supports WinForms. 

I've used the previous version with WPF without any extra tags.

Also worth trying restarting VS and deleting .vs and .obj folders. Sometimes that does some magic..

**Comment by MagicAndre1981** [comment]
I've already added those settings and updated the csproj to use last dev build from myget, no difference.

**Comment by MagicAndre1981** [comment]
I also found a similar SDK:

https://www.nuget.org/packages/MSBuild.NET.Extras.Sdk/

but here the VS2017 hangs at "Preparing Solution..." and nothing happens.

**Comment by mungojam** [comment]
> I've already added those settings and updated the csproj to use last dev build from myget, no difference.

Raise an issue with the project I reckon

**Comment by mungojam** [comment]
Fixed by https://github.com/hvanbakel/CsprojToVs2017/pull/138

Thanks @andrew-boyarshin! I'll be able to remove my hacky pre and post transforms now
