### ISSUE TITLE
Bundle the tool to be usable without manual installation

### ISSUE THREAD

**Issue by amccool** [hvanbakel/CsprojToVs2017#137]
I see a nuget has been created, could the .exe be bundled into the nuget for easier usage?   Or perhaps created into a chocolately package?

**Comment by hvanbakel** [comment]
Why would you want an exe to be in the budget package? That's not for
execution but consumption in other projects?

**Comment by hvanbakel** [comment]
Having just read [this post](
https://www.hanselman.com/blog/NETCoreCodeCoverageAsAGlobalToolWithCoverlet.aspx) that does sound appealing

**Comment by mungojam** [comment]
Yeah, I reckon that .net core global tools is a better fit than chocolatey for this sort of thing

**Comment by hvanbakel** [comment]
Note to self, this seems very achievable:
https://github.com/natemcmaster/dotnet-globaltool-templates/tree/master/src/McMaster.DotNet.GlobalTool.Templates/content/GlobalTool-CSharp

**Comment by hvanbakel** [comment]
Can someone test this when the package publishes?
https://www.nuget.org/packages/Project2015To2017.Cli/

With the net core 2.1 sdk installed do:
`dotnet tool install Project2015To2017.Cli --global`

Then you should be able to run `dotnet csproj-to-2017` along with the usual parameters.

Unfortunately it pushed 1.0.0 as a first version 😢

**Comment by hvanbakel** [comment]
Never mind, this doesn't work it only works if you target netcoreapp2.1 only. So need to figure out how to solve that, maybe different project...

**Comment by hvanbakel** [comment]
This should now work. Can some of you do some tests to verify? Looks ok to me.

I'll update the readme when no issues are found

**Comment by andrew-boyarshin** [comment]
@hvanbakel works ok, no issues found (tested on Dopamine).

**Comment by amccool** [comment]
having issues for me.  What should I look for?

`PS D:\_dev> dotnet tool uninstall Project2015To2017.Cli --global`

Tool 'project2015to2017.cli' (version '1.0.1') was successfully uninstalled.

`PS D:\_dev> dotnet tool install Project2015To2017.Cli --global`

You can invoke the tool using the following command: csproj-to-2017
Tool 'project2015to2017.cli' (version '1.0.1') was successfully installed.

`PS D:\_dev> dotnet csproj-to-2017`

No executable found matching command "dotnet-csproj-to-2017"`
