### ISSUE TITLE
Verify all files are writable before writing anything

### ISSUE THREAD

**Issue by hvanbakel** [hvanbakel/CsprojToVs2017#149]
We're now touching
cproj
assemblyinfo.cs
packages.config
nuspec file

all of those should be writable prior to writing anything

**Comment by mungojam** [comment]
Sounds good, it will need to be done after the optional check-out command has been run since that makes files writable under TFVC

**Comment by hvanbakel** [comment]
We need to reconsider this, if it is under TFVC that causes issues. We probably should warn and then continue.

**Comment by mungojam** [comment]
We could error unless the user has altered the delete op. Or to achieve the same thing, the default delete op could have the read-only error check as part of it
