### ISSUE TITLE
Redundant unconditional PropertyGroup

### ISSUE THREAD

**Issue by andrew-boyarshin** [hvanbakel/CsprojToVs2017#152]
We always create "main" PropertyGroup (for basic things like `TargetFrameworks`) and "additional" one for everything else. We need to merge these two before 2.0 release (obviously will require public API changes).

I intend to fix this one after #151.

**Comment by hvanbakel** [comment]
This is fixed in that 2.0 preparation branch.

**Comment by andrew-boyarshin** [comment]
There is a large regression in cc3a3f6. All PropertyGroups are now collapsed into the primary one (even conditional ones!). Preparing PR now...
