### ISSUE TITLE
app.config stays in project file

### ISSUE THREAD

**Issue by mungojam** [hvanbakel/CsprojToVs2017#155]
Firstly, you are famous, having been featured on [@shanselman's blog](https://www.hanselman.com/blog/UpgradingAnExistingNETProjectFilesToTheLeanNewCSPROJFormatFromNETCore.aspx)!

Watching through his youtube video on that post, he hits something I have noticed before but not reported or fixed which is that app.config gets left with a redundant entry in the project file.

I don't know what the rule should be for other .config files, but we could at least remove app.config ones.

**Comment by hvanbakel** [comment]
I did a bad commit message but this was fixed in 90c8cdce4a366135f59b446e50351c5c469f8804

**Comment by andrew-boyarshin** [comment]
@hvanbakel you can change it if you like. By amending commit (even with no changes) and force-pushing. Or by rebasing, resetting, doing commit again and force-pushing.
