### ISSUE TITLE
Implement line coloring for console output

### ISSUE THREAD

**Issue by hvanbakel** [hvanbakel/CsprojToVs2017#156]
Not entirely sure how to do this yet, but running the tool on a large project means that you might have a lot of lines being written that we should be classifying (not everything is an error).

**Comment by andrew-boyarshin** [comment]
In fact, the whole `IProgress<string>` seems like a bad choice for advanced logging.

**Comment by hvanbakel** [comment]
This is now in the 2.0 branch
