### ISSUE TITLE
Multiple unconditional PropertyGroups

### ISSUE THREAD

**Issue by andrew-boyarshin** [hvanbakel/CsprojToVs2017#159]
I have been wondering if we might be breaking something by merging all unconditional properties into one primary PropertyGroup. MSBuild doesn't support dependencies on values within one PropertyGroup, so user must separate variable value definition from its usage in e.g. condition of another property. The whole concept is weird and I'm not sure what we are to do.

**Comment by hvanbakel** [comment]
My main problem was always trying to find out why msbuild was doing what it did.

If there's a risk,I would not do it, having an additional propertygroup is not a big issue

**Comment by andrew-boyarshin** [comment]
I will create a new PR then, to address this issue. ETA: 3h.

**Comment by andrew-boyarshin** [comment]
I have also decided to refactor it to be more sophisticated. Done in #160.
