### ISSUE TITLE
Analyzers transformation not working as intended

### ISSUE THREAD

**Issue by mbp** [hvanbakel/CsprojToVs2017#16]
`<Analyzer>`element might reference local "packages" directory:

    <Analyzer Include="..\packages\AWSSDK.CloudWatch.3.3.2.2\analyzers\dotnet\cs\AWSSDK.CloudWatch.CodeAnalysis.dll" />

After conversion, this file is not found on disk (I'm not sure how this should be specified instead).

I found that when I install AWSSDK.CloudWatch using old project format, I get the `<Analyzer>` element.
But if I use the new csproj and install same package, the `<Analyzer>` element is not added.

**Comment by hvanbakel** [comment]
So I just found out what the difference is here, in VS2015, the analyzers were treated as a special reference. In 2017 though they just show up under the Nuget reference folder and are treated as a special reference there. So in that case, the analyzer reference is not needed.
