### ISSUE TITLE
Global tool package and exe are named differently

### ISSUE THREAD

**Issue by mungojam** [hvanbakel/CsprojToVs2017#162]
One comment Scott Hanselman makes on [the blog](https://www.hanselman.com/blog/UpgradingAnExistingNETProjectFilesToTheLeanNewCSPROJFormatFromNETCore.aspx) and video is that he has to type a different command to run the global tool than what it is called. I haven't used many global tools to know how common that is but it would make sense to try and align them.

**Comment by hvanbakel** [comment]
I heard that, thought about and I don’t think I want to be doing that. If I could go back and rename the entire repository and all the projects, then that might be worthwhile but I wanted something that wasn’t using any capitals and still relatively short. 

I don’t think it’s that much of a problem, yes you need to look at the page which explained how to install it, that’s a one time thing though.

**Comment by mungojam** [comment]
Perhaps we could add a note or link to the text that appears on
https://www.nuget.org/packages/Project2015To2017.Cli

I don't think we should assume that people know to look at the github
readme and some companies annoyingly block github.com

**Comment by hvanbakel** [comment]
We should absolutely be able to do that. Let’s reopen this one and make
that the ‘fix’.

**Comment by mungojam** [comment]
A couple more observations, it actually tells you when installing what the command is:

> C:\Users\mark\source\repos\CsprojToVs2017>dotnet tool install --global Project2015To2017.Cli
**You can invoke the tool using the following command: csproj-to-2017**
Tool 'project2015to2017.cli' (version '1.8.1') was successfully installed.

I can see the difficulty you had as I don't think hyphens are allowed in the package name. I see some other global tools like NuKeeper use PascalCase for their main exe:

>C:\Users\mark\source\repos\CsprojToVs2017>dotnet tool install --global NuKeeper
You can invoke the tool using the following command: **NuKeeper**
Tool 'nukeeper' (version '0.6.3') was successfully installed.

so you could go for CsProjTo2017 for the package name and tool exe. But your call

**Comment by hvanbakel** [comment]
Done, see here:
https://www.nuget.org/packages/Project2015To2017.Cli

**Comment by hvanbakel** [comment]
I might look into aliases for the tool later but for now this works I guess.

**Comment by andrew-boyarshin** [comment]
@hvanbakel I like your idea mentioned in #169. I'd like to elaborate on the way I see it would be even better.

```batch
> dotnet migrate-2017
(usage help)
> dotnet migrate-2017 evaluate
rem like Console --dry-run, but also output statistics on a number of projects and analysis warnings in each, preferably in a table
> dotnet migrate-2017 execute
rem normal full execution
> dotnet migrate-2017 modernize
rem check if not yet migrated, then perform PCL to .NET Standard conversion, remove legacy `DebugType`s, etc
```

No need to specify the directory explicitly, automatically select:
* if there is the only _.sln_ file in cwd - process it, abort selection
* else if there is the only _.(cs)proj_ file in cwd - process it, abort selection
* output help message

That is, no recursive directory descent at all (standalone Console might still do that), to match other `dotnet` tools' behavior.

**Comment by andrew-boyarshin** [comment]
Further to this point, it appears the following NuGet packages must be created:
* X.Core (containing all but listed below)
* X.Diagnostics (move all from X.Analysis.Diagnostics)
* X.Migrate2017 (move all but `TargetFrameworkTransformation` from X.Transforms, most of ProjectConverter logic), depends on X.Core
* X.Standalone (instead of Console, probably gets deprecated), depends on X.Migrate2017, X.Diagnostics
* X.Migrate2017.Cli (instead of Console flavor), depends on X.Migrate2017, X.Diagnostics

This way, possible .NET Core 3.0 growth goes this way:
* X.Core remains mostly stable
* X.Diagnostics just gets more diagnostics
* X.Migrate2017 and X.Migrate2017.Cli - nothing, this doesn't relate to that
* X.MigrateCore3 (new package with new transformations), depends on X.Core
* X.MigrateCore3.Cli (new package), depends on X.MigrateCore3, X.Diagnostics
* X.Standalone gets deprecated: added dependency on X.MigrateCore3; or gets removed as deprecated

**Comment by mungojam** [comment]
Not sure I agree with creating lots of packages like that. What is the distinct use of each individual one? If you're thinking it might be something that does everything to do with project files, then something based on buildalizer might be better.

I liked your ideas in the previous post though. `modernize` could also be an option when transforming. I know I would use the modernize command on things I've already converted

**Comment by andrew-boyarshin** [comment]
@mungojam Core is responsible of reading and writing all project related data. Other packages depend on Core to provide the required functionality. Each kind of migration (to VS15, to .NET Core 3.0) has a different set of (library+CLI command) packages. Plus analyzers are common for all migration kinds (could be kept in Core, but I see no reason not to split into different package).
Tools based on MSBuild might indeed suit one's needs well. But there is a difference between the full-blown MSBuild engine + all .props and .targets and .DLLs VS small library to handle that without any evaluation.

**Comment by andrew-boyarshin** [comment]
@hvanbakel what do you think on these 2 my proposals (dotnet-tools and NuGet packages)?

**Comment by hvanbakel** [comment]
I don't think we need to create that many packages, things like MigrateCore3 we can probably skip. Each cli or global tool package can just pick from the transformations in core.

So I think we should be fine with having
A core package, maybe without a suffix like now, packaged up for people extending it with additional transformations
A netfx cli, doesn't need to be a package is just output delivered through a release like now
A global tool delivered as a package, this last one can then be made specific to the type of transformation, like to 2017 or to net core x

We can still decide to split the code into multiple projects, like the transforms specific to 2017 or the analyzers. Project doesn't have to be package though.

**Comment by mungojam** [comment]
> We can still decide to split the code into multiple projects, like the transforms specific to 2017 or the analyzers. Project doesn't have to be package though.

At work I couldn't actually figure out how to include multiple projects in a package with the new format, so if we manage it then that's great for me 😎

**Comment by andrew-boyarshin** [comment]
What is the point of splitting e.g. VS15 transforms into project if they are still delivered in the Core package? The whole point was to separate Core functionality that others might depend on, and VS15 migration that only `dotnet migrate-2017` and standalone app will likely depend on, was it not?

And honestly speaking, after introduction of `dotnet migrate-2017` there is little point in standalone (Console) app, except support of recursive directory tree descent.

Ok, reduced plan is (in projects and packages):
* X.Core (or merely X; library), some diagnostics inside
* X.Migrate2017 (library), specific diagnostics inside, most currently present transforms
* X.Standalone (or X.Console, app)
* X.Migrate2017.DotNetTool (app)

And we could reconsider namespace choice (Project2015To2017 won't make sense if any additional migrations will be implemented).

**Comment by hvanbakel** [comment]
I was trying to say that there is a difference between project structure and package structure. 

If, and that is if, we want to split out the core project that would make it clearer as to what the transform is for. I’m fine with having everything in one project and just namespace them out.

As to your specific package `X.Migrate2017` this is the ‘option’ that the tool uses, correct? So we will be creating a single tool with multiple commands. And `X.Standalone` is the current NetFx .exe? We don’t need to deliver that one through nuget in my opinion.

**Comment by mungojam** [comment]
@andrew-boyarshin 
> but with major ideological differences

I agree, and I think I am more aligned with @hvanbakel here. The original purpose of the tool was to provide a converter from old style projects to the new SDK style projects, not to provide a general purpose tool for working with project files, though I recognise that could be useful to some people. 

I think the majority of the devs who use the tool as a converter will not have a solid grasp of MSBuild (that includes me). For my own needs at work, I want it to just do the best it can at converting the project so I am left with as minimal project file as possible. I'm personally happy for it to make opinionated changes such as switching to the portable pdbs because those are the new default and like most devs we don't have specific dependencies in this area, we just use VS tooling for debugging. In our 50+ solutions, we have only tweaked the project files twice, so I'm really after a perfect conversion of VS produced project files so we have a clean slate.

I'm happy for us to add some further nice things like the warnings that you have been adding although some of those I think we should just be bolder and make the change, like changing references to package references like we do for test projects. For those devs that know about these things, they can easily revert it, and for those who don't, they will just end up with a better result 95% of the time.

Back to the main purpose, I think you may be keen to see this as a general purpose tool/package for working with projects, and maybe that's where you see X.Core fitting. I think you should find out if there is a market for such a tool first and whether Buildalizer is a better place to focus efforts on that. I for one am not particularly motivated to commit time to anything other than the transformation with optional modernisation. I would rather focus time on helping with Buildalizer if I did want to help more generally.

You have some good ideas, so keep raising them as standalone issues and we can have some good debate. I will probably disagree with some or want them refined, e.g. I rely on recursive directory processing because I want to migrate many solutions in one go, though I could of course implement that looping myself.

**Comment by andrew-boyarshin** [comment]
@mungojam
The only (almost) reason I want to separate VS2015->VS2017 transformations into separate library is to make way for possible future expansion onto another kind of project conversion/migration, like (presumably) .NET Core 3.0. I don't intend to make it so generic, but only a bit more extensible in the very direction this project is initially aimed. That will to make it even better architecturally structured is actually my secondary reason for suggesting separation of these transformations.
Tool is already opinionated, and I intend to make it more opinionated through `modernize` implementation, but I honestly think this should be optional, not mandatory. Having to type one more command doesn't seem too bad for me.
Reasons why I'm spending time on this project are: I've got nothing else in particular to do (I'm entering university this September), and I used this project to great success and I want to share some gratitude for that in the form of improvements.
Regarding recursive descent - why not make it optional, or even better - add globbing, so your requirements could be satisfied with sth like:
```batch
> dotnet migrate-2017 execute **\*.sln
rem walks the subtree of cwd and converts all *.sln files and their projects
```
I believe after 2.0 release (I believe it is ready to ship now) I can send PRs and we can see then how it goes, although I'd prefer to have at least some initial coordination of efforts and ideas before that. I guess this discussion served as the beginning of the latter.

**Comment by mungojam** [comment]
@andrew-boyarshin thanks for the great reply, it's good to understand where you are coming from on these things. What are you going to study at uni? Computer Science or something else? I'm sure you'll do great at it!

> another kind of project conversion/migration, like (presumably) .NET Core 3.0

I expect I will be converting our projects to .net core 3, so in theory it could be useful. However, I feel like the benefit of the new project format is that this will be very easy to do by anybody with just a find/replace of the TargetFramework. That's how I plan to do it anyway. I guess maybe a find/replace of the ExtrasSDK too if we have used it for WPF and no longer need to. But that's all nothing compared to the SDK project conversion which I could never have managed for all our projects.

> modernize implementation, but I honestly think this should be optional, not mandatory. Having to type one more command doesn't seem too bad for me.

I can understand that point of view, one for @hvanbakel to decide on probably. I think it should be optional but default, or at least an easy flag.

```
> dotnet migrate-2017 execute **\*.sln
rem walks the subtree of cwd and converts all *.sln files and their projects
```

Nice idea, I'd be happy with that as long as I could use globbing with the nuget package too
