### ISSUE TITLE
Project file  not supported

### ISSUE THREAD

**Issue by clarity99** [hvanbakel/CsprojToVs2017#164]
When running the tool on an asp.net mvc project I get:
Project found: cryptoportfolio\cryptoportfolio.csproj
No nuspec found, skipping package configuration.
This project type is not supported for conversion.

I there a list of what projects are supported? I've only found a reference somewhere in the issues that Xamarin and WinForms are not supported.

**Comment by andrew-boyarshin** [comment]
ASP.NET is not really supported by new VS project system (CPS), so we better bail out sooner with a descriptive message rather than try to convert and leave user to tackle the appearing issues.

**Comment by andrew-boyarshin** [comment]
Tracking issue <https://github.com/dotnet/project-system/issues/2670>.

**Comment by hvanbakel** [comment]
We should put this in the readme.

**Comment by morindo** [comment]
Hi guys, just want to let you know that using the great [CsprojToVs2017](https://github.com/hvanbakel/CsprojToVs2017) tool it's easy to migrate your MVC projects to the great great [MSBuild.SDK.SystemWeb](https://github.com/CZEMacLeod/MSBuild.SDK.SystemWeb) Sdk style.

Just remove the <ProjectTypeGuids>{349c5851-65df-11da-9384-00065b846f21};{fae04ec0-301f-11d3-bf4b-00c04f79efbc}</ProjectTypeGuids> from your csproj, it will then act as default project type (Class Library), you will then be able to migrate your project to <Project Sdk="Microsoft.NET.Sdk"> using the command dotnet migrate-2019 wizard "D:\Path\To\My\TestProject.csproj". Then just replace the Sdk attribute with <Project Sdk="MSBuild.SDK.SystemWeb/4.0.82"> and voilà!

Just want to thank @CZEMacLeod for your great job on this one! It just works!
