### ISSUE TITLE
Decide a course of actions for unsupported BeforeBuild and AfterBuild

### ISSUE THREAD

**Issue by andrew-boyarshin** [hvanbakel/CsprojToVs2017#172]
CPS doesn't support redefining BeforeBuild and AfterBuild targets despite the XML comments in _Microsoft.Common.CurrentVersion.targets_.

<https://github.com/Microsoft/msbuild/issues/1680>

Suggestion:
Rewrite targets redefinition. **BeforeBuild**:
```xml
<Target Name="BeforeBuildMigrated" BeforeTargets="PreBuildEvent">...</Target>
```
**AfterBuild**:
```xml
<PropertyGroup>
    <BuildDependsOn>$(BuildDependsOn);AfterBuildMigrated</BuildDependsOn>
</PropertGroup>
<Target Name="AfterBuildMigrated">...</Target>
```

**Comment by hvanbakel** [comment]
So for targets that come from nuget packages, we should be removing those. They end up in a generated file in the `obj` folder. 

If someone has defined them in the csproj itself, then we could do what you suggested but are those equivalent? So is running before `PreBuildEvent' equal to `BeforeBuild`? There might be assumptions in those targets that no longer hold in that case. Which is again, in my opnion, something that would be the 1% case which the user can solve himself.

I don't think we should try and make this a run once and everything is solved. That should be the case for the 'normal' projects but complex things with conditions, custom targets and all that would be fine with me if that needs some manual work.

**Comment by andrew-boyarshin** [comment]
I believe we should leave user to handle as little manual modifications as possible. What I proposed has almost the same behavior as in legacy project system. Approach I selected for `AfterBuild` would give precisely the same behavior as in legacy system, approach I selected for `BeforeBuild` might be a bit later than was before, still before any actual build takes place. So I believe they are 99% compatible with pre-CPS behavior and I see no reason why this shouldn't be a transformation.

**Comment by hvanbakel** [comment]
I see what you're saying, I'm not saying we shouldn't do it but I want to
be very cautious when adding something that will work in most but not all
cases. If we don't know how to handle something we should leave it and have
the user go in.

The users that do this kind of stuff are well capapble of fixing these last
issues themselves.

I know what the capabilities are for things like this I've just always
found the msbuild stuff too arcane and error prone to build something in.

**Comment by andrew-boyarshin** [comment]
I am amazed at how capable MSBuild really is (since 15.6/7 it can even compile C# Task code from e.g. some property thanks to Roslyn). To be completely sure how MSBuild works (when I work on some complex configuration things), I use MSBuildStructuredLogger, it even has evaluation log, as well as execution task tree. I'm fairly sure that the difference between executing action at the moment of `BeforeBuild` and guaranteed execution before `PreBuildEvent` is fired won't play any difference for our users.
