### ISSUE TITLE
Add example of how to use NuGet package to readme

### ISSUE THREAD

**Issue by mungojam** [hvanbakel/CsprojToVs2017#185]

**Comment by VladDerptastic** [comment]
Any update on this one? :)

**Comment by mungojam** [comment]
@VladDerptastic are you hoping to add it to an existing .net solution and customise? Or do you just need a .net global tool. It's no longer clear how to do the first with the newer versions (see some discussion on https://github.com/hvanbakel/CsprojToVs2017/issues/238)

@andrew-boyarshin it would be good if you can create an example that consumes the existing version as a package and adds a custom transform so that people (including me) can understand the intended way to do it. I knew how to do it with the old version but I'm a bit lost with the new one.

**Comment by andrew-boyarshin** [comment]
@hvanbakel what about creating `Project2015To2017.Core`, `Project2015To2017.Migrate2017.Library` and `Project2015To2017.Migrate2019.Library` NuGet packages? If you do that, I can do the rest and provide necessary samples. I mean, I'm sure it can be consumed right now as they are, but it requires more care with handling implicit dependencies.

**Comment by VladDerptastic** [comment]
@mungojam  The first option. I was hoping it would contain an API that would allow me to use it, in an internal project.

**Comment by mungojam** [comment]
I've started a PR #243, feel free to contribute/fork

**Comment by hvanbakel** [comment]
I just saw, we also need to setup the nuget push but that’s something that
I can do, I need to generate keys for that and update the appveyor
definition.

**Comment by mungojam** [comment]
@VladDerptastic  there is now [a beta version](https://www.nuget.org/packages/Project2015To2017/4.1.0-beta.2) of the package that you can use from your own code to achieve things like this. I've updated the readme with a basic example of using the package.

If you get a chance to try it, please let us know how you get on

**Comment by VladDerptastic** [comment]
@mungojam Cheers! It might take me some time to get back to that project, but I'll give it a spin as soon as possible. :)
