### ISSUE TITLE
How does this handle project.json references?

### ISSUE THREAD

**Issue by Wil73** [hvanbakel/CsprojToVs2017#20]
Does this work for all types of projects or only a select list?

Which project types does this work for?

Project.Json does not include references in .csproj files, how does this handle those references?

**Comment by hvanbakel** [comment]
There is no plan on supporting project.json. This project is assuming a regular 2015 project without all the steps Microsoft took in between.

So it should work for a pre 2017 csproj file, and it only tries to optimize it to the new csproj format. I've tested with class libraries/web projects/console apps etc.
