### ISSUE TITLE
Enable keeping assemplyinfo.cs in the project by an option in the command-line

### ISSUE THREAD

**Issue by moh-hassan** [hvanbakel/CsprojToVs2017#205]
### **1) Keep Assemplyinfo.cs and don't move it to the backup folder**
Some applications are still depend on `assemplyinfo.cs` as a source for information stored in  `AssemplyAtrributes` and used by application by `Reflection`. The application may fire an exception if these AssemplyAtrributes are null.

Also, assemplyinfo.cs  include important attributes needed for unit test like:

		[assembly: InternalsVisibleTo ...]
		
**My suggestion:**
a) Enable keeping of assemplyinfo.cs in the project.
    It can be controlled by an option in the command-line, eg 

		--keepAssemply
		
b) Read the file(s) and update csproj by their corresponding info. (that is already done)
c)Add this line (mandatory) to the project:

		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
otherwise the build phase generate this file again in bin folder which cause troubles in compilation.

### **2)Resolve the next problem:**
In case of existing more than one file containing `AssemplyAtrributes`, the next warn is displayed:
>[ WRN] Could not read from assemblyinfo, multiple assemblyinfo files found:
SharedAssemblyInfo.cs,
Properties\AssemblyInfo.cs	

and the migration tool don't copy  AssemplyAtrributes values into the corresponding property in csproj.

The Project may contain more than file with different names like `version.cs ,sharedassemply.cs and assemplyinfo.cs`, but sure there is no duplication for any of the `AssemplyAtrributes` (otherwise the compiler raise an error)

**My suggestion:** 
a)Read all the files that contain [assembly:* (already the tool discovered these files)
b)Update csproj by their corresponding info.
c)replace that WRN with something like: 
>[INF] Moving attributes from file1,file2,.. and AssemblyInfo to project file

d)Apply the rules of keeping of `assemplyinfo.cs `in the project as described in (1)

**Comment by hvanbakel** [comment]
1, is not an issue, that flag already exists, have a look at the flags section of the readme. If there are attributes that have non default values it should keep the file anyway. Is that not what you're seeing?

2, to do what you're saying we would need to parse the source which we currently don't do. The check is if the file ends with assemblyinfo.cs. I don't think this is common enough to legitimize parsing every single source file to see if it might include an attribute.

**Comment by moh-hassan** [comment]
With (1), sure it isn't an issue, but good catch for the flags. I will try it.

With (2), the migration tool already find the assemblies and mention the name of the files, but warn as 'could not read from assemply info.

This is the warn message:
>[ WRN] Could not read from assemblyinfo, multiple assemblyinfo files found:
SharedAssemblyInfo.cs,
Properties\AssemblyInfo.cs

So, I expect that as the migration tool discovered the two assemblies  `SharedAssemblyInfo.cs, prroperties\AssemblyInfo.cs', it should read it not give this warning.

**Comment by hvanbakel** [comment]
With that part for 2, I agree 👍 

In your initial issue you suggested that it could be any file, that would involve parsing every single source file which is not impossible but it’s a bit ‘much’ for a conversion. We can see if we can read from all of them instead of just one.

**Comment by andrew-boyarshin** [comment]
The problem with shared AssemblyInfos is that they are likely used in multiple projects, with different "private" AssemblyInfos.
1. We don't know all possible projects which use this file
2. We can't assume about contents of shared files, they might have preprocessor directives on compilation constants unique for each project.

Overall it can be implemented, but certainly forbidden by default.

**Comment by moh-hassan** [comment]
Thank you :+1:
