### ISSUE TITLE
Prevent it from trying to upgrade .NET 4+ MVC projects

### ISSUE THREAD

**Issue by nazjunaid** [hvanbakel/CsprojToVs2017#21]
The tools upgrades .NET MVC projects which are not compatible from what I understand with the 2017 csproj format. Maybe it shouldn't let you do this?

**Comment by hvanbakel** [comment]
Can you give an example of a project file and the specific section that it
should look for?

**Comment by nazjunaid** [comment]
I believe it's related to

https://github.com/aspnet/Home/issues/1978 and https://github.com/dotnet/sdk/issues/491

It messes up on nested types liek Gobal.asax and Webconfig transforms you can detect them for looking for the <DependentUpon> attribute

**Comment by hvanbakel** [comment]
@nazjunaid if you can give me something to work/test with, that would be extremely helpful

**Comment by morindo** [comment]
Hi guys, just want to let you know that using the great [CsprojToVs2017](https://github.com/hvanbakel/CsprojToVs2017) tool it's easy to migrate your MVC projects to the great great [MSBuild.SDK.SystemWeb](https://github.com/CZEMacLeod/MSBuild.SDK.SystemWeb) Sdk style.

Just remove the <ProjectTypeGuids>{349c5851-65df-11da-9384-00065b846f21};{fae04ec0-301f-11d3-bf4b-00c04f79efbc}</ProjectTypeGuids> from your csproj, it will then act as default project type (Class Library), you will then be able to migrate your project to <Project Sdk="Microsoft.NET.Sdk"> using the command dotnet migrate-2019 wizard "D:\Path\To\My\TestProject.csproj". Then just replace the Sdk attribute with <Project Sdk="MSBuild.SDK.SystemWeb/4.0.82"> and voilà!

Just want to thank @CZEMacLeod for your great job on this one! It just works!
