### ISSUE TITLE
VB support

### ISSUE THREAD

**Issue by baruchiro** [hvanbakel/CsprojToVs2017#211]
The AssemblyInfo.vb located in "My Project" subfolder.

**Comment by hvanbakel** [comment]
We make assumptions about where to find assembly info files, there’s no other way really. The only other way is to parse and/or compile the entire project which is not something we want to do as part of conversion. There’s not that many cases where people actually move that file, and nothing breaks if we don’t find one (as far as I know). So while suboptimal, I don’t see a way of solving this.

**Comment by baruchiro** [comment]
I think that I do not understand.
If we make assumptions, why "My Project" it is not one of our assumptions?
If you open VS and create new VB Console Application project, you will find the AssemblyInfo.vb in "My Project" folder.
