### ISSUE TITLE
csproj validation rules

### ISSUE THREAD

**Issue by baruchiro** [hvanbakel/CsprojToVs2017#214]
Hi, I want to use your code to validate my new (and old) csproj file.
It includes rules like validating 'Company' value, paths absolute to the solution and so.

Can you suggest a way to handle it?

**Comment by hvanbakel** [comment]
When you say validating, do you mean assuring that it has a certain value for example as part of a CI process?

The difficulty is that is can be in 2 places now, either as an assembly attribute or in the project file. And finding out if it is an assembly attribute means either applying heuristics regarding the path or compiling the project and reading the outputted binary.

**Comment by baruchiro** [comment]
Yes, like CI pipeline.
So let's leave the old csproj and assembly, and focus just on new csproj, validating that in all new csproj we write the "Company" tag, for example.

What will be the best way to do this?

**Comment by baruchiro** [comment]
No, that's for the job.
But you are right, there is MSBuild /validate option to achieve that.

Thank you!🙏
