### ISSUE TITLE
Keep AssemblyName if it is not default

### ISSUE THREAD

**Issue by baruchiro** [hvanbakel/CsprojToVs2017#215]
In new csproj, the assembly name is the namespace name by default.
However, if the assembly name in old csproj is not the same as the namespace, we should keep it and log to the user.

**Comment by hvanbakel** [comment]
Are you sure this is an issue, there’s a bunch of code for checking this (among others here CsprojToVs2017/Project2015To2017.Core/Transforms/PropertySimplificationTransformation.cs)

**Comment by andrew-boyarshin** [comment]
Indeed there is a lot of code to handle these cases correctly. Could you please share example of project file where it is not handled correctly?

**Comment by hvanbakel** [comment]
Closing now due to lack of detail
