### ISSUE TITLE
Unable to resolve dependency 'Project2015To2017.Core'.

### ISSUE THREAD

**Issue by Kantuz001** [hvanbakel/CsprojToVs2017#218]
Error while installing nuget https://www.nuget.org/packages/Project2015To2017

Dependencies of this nuget are
NETStandard 1.3

NETStandard.Library (>= 1.6.1)
Project2015To2017.Core (>= 3.0.5)
Project2015To2017.Migrate2017.Library (>= 3.0.5)
.NETStandard 2.0

Project2015To2017.Core (>= 3.0.5)
Project2015To2017.Migrate2017.Library (>= 3.0.5)

So i git error
Unable to resolve dependency 'Project2015To2017.Core'

I tried to find dependency  in nuget
https://www.nuget.org/packages/Project2015To2017.Core/ does not exist

**Comment by hvanbakel** [comment]
If this is a dependency, then what package are you trying to install as that's where (part of) the issue is

**Comment by Kantuz001** [comment]
> If this is a dependency, then what package are you trying to install as that's where (part of) the issue is

added comments

**Comment by andrew-boyarshin** [comment]
Regression in my PR #200.

**Comment by andrew-boyarshin** [comment]
The correct way to fix would be to create new NuGet packages (`.Core` and `.Migrate2017.Library`) and push them the same way root package does.
The workaround way would require some MSBuild trickery (translate `ProjectReference`s to `Reference`s for generated nuspec).

**Comment by hvanbakel** [comment]
I won't be near a PC for the next three days, but we need to be careful here as the global tool depends on the nupkg without the .core suffix.

I don't fully understand how we got into this state really

**Comment by hvanbakel** [comment]
@andrew-boyarshin I get that it comes from the tricks in 
CsprojToVs2017/Project2015To2017/Project2015To2017.csproj

That's what makes the project reference a dependency, correct? If that's the case, we could just include the dlls directly, right?

**Comment by hvanbakel** [comment]
I've unlisted everytyhing > 3.0.2 so we can fix this without the old package being unusable.

**Comment by andrew-boyarshin** [comment]
@hvanbakel tricks in `Project2015To2017.csproj` allow DLLs to be included in resulting `nupkg`, thus `nupkg` is self-contained. But `nuspec` file (generated by MSBuild) isn't aware of that. MSBuild adds `ProjectReference`s as dependencies even though they are present in the list of outputs to pack.

**Comment by andrew-boyarshin** [comment]
Suggestion: add `PrivateAssets="All"` to all `ProjectReference`s in `Project2015To2017.csproj`.
