### ISSUE TITLE
PackageReference dependencies should be copied from the old csproj file

### ISSUE THREAD

**Issue by arnoldpistorius** [hvanbakel/CsprojToVs2017#22]
When I use your tool with a project which already uses PackageReference, but not the new csproj style, the tool doesn't recognize any nuget packages. Even the existing PackageReference packages are not copied in to the new configuration.

I'm happy your tool creates a backup file of the old csproj file, so I can copy/paste the PackageReference manually. But this could/should be done by the tool itself.

**Comment by robbratton** [comment]
Please give a sample csproj with references.

**Comment by hvanbakel** [comment]
Will fix this one soon, shouldn't be too hard. We can take the output file and copy one of the new package references into an old csproj.
