### ISSUE TITLE
Unable to resolve dependency 'Microsoft.DotNet.Cli.CommandLine'

### ISSUE THREAD

**Issue by AmitGee** [hvanbakel/CsprojToVs2017#221]
When attempting to install this nuget package (version 3.0.6) I get this error:

Unable to resolve dependency 'Microsoft.DotNet.Cli.CommandLine'

Sure enough this package doesn't exist in Nuget

**Comment by andrew-boyarshin** [comment]
Something is wrong. 3.0.7 still lists 'Microsoft.DotNet.Cli.CommandLine' as NuGet dependency.

**Comment by andrew-boyarshin** [comment]
@hvanbakel is the release on NuGet the same as AppVeyor artifact? Feels like the NuGet release wasn't built with `-p:Pack=true`.

**Comment by andrew-boyarshin** [comment]
Yep. Confirmed fixed as of 0bb15a295a004a875519b0b43a176067867ebb3e. @hvanbakel a new hotfix release would be nice.

**Comment by hvanbakel** [comment]
New release is building
