### ISSUE TITLE
System.Runtime.Caching is misused

### ISSUE THREAD

**Issue by andrew-boyarshin** [hvanbakel/CsprojToVs2017#223]
Fatal error, application stops.
```System.Runtime.Caching is not supported on this platform.```
WSL, Ubuntu 18.04, dotnet-sdk-2.2.
We have dependency on `System.Runtime.Caching` in `netstandard` library, hence no Unix support.
It appears if we change TFM to `netcoreapp` (no less than 2.0) we could pull in real implementation. 
[corefx#26172](https://github.com/dotnet/corefx/issues/26172)
Not sure how to proceed for now, a little busy ATM. For now - `dotnet migrate-2017` works only on Windows.

**Comment by andrew-boyarshin** [comment]
A good idea would be to use multitargetting: `netcoreapp2.0` and `net45` will use modern cache (using `System.Runtime.Caching`), `netstandard1.3` will use old dictionary-based implementation. This will retain the TFM coverage while allowing the `System.Runtime.Caching` to use platform-specific implementations.

**Comment by Identifier** [comment]
I just ran into this same error message, but I am on Windows 10 with dotnet version 2.1.402:

C:\MyProject>dotnet migrate-2017 migrate MyProject.csproj
[07:50:12 INF] Reading assembly info from C:\MyProject\Properties\AssemblyInfo.cs.
[07:50:12 INF] Moving attributes from AssemblyInfo to project file
[07:50:12 FTL] System.Runtime.Caching is not supported on this platform.

So perhaps it's unrelated to your platform.  Is there something Windows users need to install to add support for System.Runtime.Caching?

**Comment by andrew-boyarshin** [comment]
All right, non-Unix specific. It appears on all platforms except for .NET Framework (since there it is redirected to framework assembly). High priority it seems. My solution (proposed above) should work.

**Comment by hvanbakel** [comment]
Quick fix could be to disable it altogether for now? It's an optimization
anyway.

**Comment by andrew-boyarshin** [comment]
That would work too.

**Comment by hvanbakel** [comment]
I'll put that in later today

**Comment by hvanbakel** [comment]
@andrew-boyarshin so we were already multi targeting, and from the changes I can't tell really what broke other than if something changed on AppVeyor.... I built it locally on my box and it worked just fine.

Anyway, it now uses the legacy cache which works
