### ISSUE TITLE
Not working with multiple project files in the directory

### ISSUE THREAD

**Issue by a-carvallo** [hvanbakel/CsprojToVs2017#228]
Hello,

I wanted to convert a project but it wouldn't work, saying to `Specify which project file to use because <x> contains more than one project file.`, even when I specified it.

After searching a bit it would seem that it's actually on dotnet's side: https://github.com/dotnet/cli/issues/4808

(Also another tool having a similar issue: https://github.com/nil4/dotnet-transform-xdt/issues/14)

(In case the issue happens for someone else it might be a reference.)

**Comment by arialdomartini** [comment]
I confirm the problem, even if the issue has been closed.
