### ISSUE TITLE
Create migrate-2019

### ISSUE THREAD

**Issue by andrew-boyarshin** [hvanbakel/CsprojToVs2017#234]
This will allow us to drop old VS15 assumptions and convert WPF & WinForms projects better.

The implementation would require:
* Creation of `.Migrate2019.Library` and `.Migrate2019.Tool`
* Reference `.Migrate2017.Library` from `.Migrate2019.Tool` (or we would be unable to reuse existing transformations)
* Implement some alternative transformations (for WPF & Windows Forms)
* Pass parameter (enum?) to existing transformations to indicate target VS version (e.g. `PropertySimplificationTransformation`)

**Comment by hvanbakel** [comment]
I assume we would make this work on both 2015 and 2017 project files? So you can go from 2015 straight to 2019 if you want?

Are there any other changes that you are aware of besides WPF/WinForms?

**Comment by andrew-boyarshin** [comment]
Yes, migrate-2019 should migrate from both pre-2017 and 2017.
In 2019 we can simplify projects even more (`PropertySimplificationTransformation`).

**Comment by andrew-boyarshin** [comment]
Latest _master_ contains the starter pack for this issue. :)

**Comment by win32nipuh** [comment]
How to register and use migrate-2019 tool?

**Comment by andrew-boyarshin** [comment]
@win32nipuh You can't now. It's not published yet (although I do have some code on my local repo). I'm too busy at the moment. Probably in the end of June it is for me, if neither @hvanbakel nor @mungojam step in and implement it. It is also dependent on #243.

**Comment by andrew-boyarshin** [comment]
This is actually done as of 4.1. Closing.
