### ISSUE TITLE
Convert deterministic flag when needed

### ISSUE THREAD

**Issue by pablocar80** [hvanbakel/CsprojToVs2017#237]
The previous format allowed to use wildcards in version numbers, so that the compiler would automatically generate build numbers based on current time and date.

After conversion, they generate lines like the following:
```
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.9.*")]
[assembly: System.Reflection.AssemblyVersionAttribute("0.9.*")]
```

However these newly converted lines give error code CS8357: The specified version string contains wildcards, which are not compatible with determinism. Either remove wildcards from the version string, or disable determinism for this compilation.

The reason for this is that in the new format, wildcards are forbidden by default. The only way to allow wildcards is to turn off "determinism". Determinism means that if the compiler receives the same input it generates the same output, and the timestamps break that.

To migrate projects with wildcards, the following line is needed:

`<Deterministic>False</Deterministic>`

Some more information on [StackOverflow](https://stackoverflow.com/questions/43019832/auto-versioning-in-visual-studio-2017-net-core/46985624#46985624)

**Comment by mungojam** [comment]
I didSounds like a good way , I think that deterministic build is a fairly recent thing

**Comment by hvanbakel** [comment]
I'm inclined to say that we don't want to make this the default behavior. This is up to the developer to decide which way to go. The fact that you don't get a warning/error doesn't mean the chosen solution is better.

**Comment by pablocar80** [comment]
There isn't really any decision made by adding the deterministic flag. The user had already chosen to use auto-generated numbers in their previous project, which made the project non-deterministic. The new format requires explicitly saying that you're using auto generated numbers and that you also understand the consequences of doing so.

If you want to still leave the door open as an opportunity to reconsider the auto-generated, how about a simple warning? Otherwise the tool is introducing compile errors, and the first reaction is to think that the tool screwed the project.

**Comment by hvanbakel** [comment]
I can see us warning about putting in that flag. I like your reasoning
around the current implications of the wildcards
