### ISSUE TITLE
Project2015to2017 nuget library doesn't specify required nuget packages

### ISSUE THREAD

**Issue by mungojam** [hvanbakel/CsprojToVs2017#238]
I thought I'd try upgrading my custom converter to the latest version but I found that I had to manually add a package reference to `Microsoft.Extensions.Logging.Abstractions` which is clearly a requirement of the library but isn't specified as such [on nuget](https://www.nuget.org/packages/Project2015To2017)

It also requires CodeAnalysis and nuget.configuration libraries. Not sure why they haven't ended up in the dependencies automatically.

I should be able to get it up and running soon, looking forward to seeing how it does :)

**Comment by andrew-boyarshin** [comment]
Because to preserve Project2015To2017 library being a single NuGet package (not my choice) I had to include some MSBuild trickery. This is a bit fragile. I would've just created more NuGet packages and replaced primary one with a dummy for dependencies' sake. Visual Studio does it like this (lots of NuGet packages), I see no problem in that.

**Comment by hvanbakel** [comment]
We might do so in the near future now that we've given people a migration
path where the tool indicates what the replacement package is. At the time
that wasn't the case yet.

The global tool is now downloaded over 10 times more often than the
original library. I would give it another month or so and then make the cut
we've kept the old package alive long enough at that point.

**Comment by mungojam** [comment]
Presum

**Comment by andrew-boyarshin** [comment]
You mean adding the global tool as a NuGet package? This can't be right. The correct way now is to reference the `Project2015To2017` NuGet (as before, but care about implicit dependencies), although I would've probably just added this repo as git submodule and used `ProjectReference` directly. The way to go in the future (4.1?) would be creating separate NuGet packages for each project.

**Comment by mungojam** [comment]
Looks like I may need to give up on this version and go back to a much older one. There are various things that don't seem to work anymore when consuming as a package. For example I had a custom transform that was adding to `project.AssemblyAttributeProperties`, however they are no longer getting written out to the project file by the writer. I'm also clearing out the existing version tags but they are getting included anyway.

I expect I need to do it through the default property group, but unfortunately I don't have the time to work through it at this stage so I'll just go back to the older version instead.

**Comment by hvanbakel** [comment]
FYI, the build failed so none of the artifacts were created, looking at
that now.

**Comment by hvanbakel** [comment]
And it went through now, it's published as a beta version
