### ISSUE TITLE
Proposal: add "migrate" as tag or in description

### ISSUE THREAD

**Issue by 304NotModified** [hvanbakel/CsprojToVs2017#250]
Hi,

Thanks for this excellent tool :)

I found it a bit hard to find this repo after some long time. The reason? I'm searching for "csproj migrate" 👼 

See these screenshots:

1. search for "csproj migrate"

    ![image](https://user-images.githubusercontent.com/5808377/58838458-ffe8b780-865e-11e9-869c-518f66b11597.png)

2. Search for "csproj migration" (that one works!)

    ![image](https://user-images.githubusercontent.com/5808377/58838429-f2333200-865e-11e9-9ff3-c2ec34f432aa.png)

---

So proposal: add "migrate" to the tags or description :)

![image](https://user-images.githubusercontent.com/5808377/58838403-e5aed980-865e-11e9-81e9-f4216ecfc669.png)

**Comment by hvanbakel** [comment]
Added, thanks for the tip.
