### ISSUE TITLE
Migration removes all .cs files

### ISSUE THREAD

**Issue by josh-degraw** [hvanbakel/CsprojToVs2017#252]
I've used this tool before without issue, but I just ran it on a solution with several projects and encountered a weird issue where it added a line in the modified `.csproj` files that for each `MyFile.cs` it found, it added the line:

```xml
<Compile Remove="MyFile.cs"/>
```

which, as the syntax implies, completely removed the files from the project-- they were all empty. It was simple enough to fix, but it seems like something that just shouldn't happen in the first place. This _seems_ like a similar issue to #210, but in my case these were all just class library projects utilized in an `ASP.NET` `MVC` project, not WinForms, and none of the files were `SubType`'d.

**Comment by mungojam** [comment]
Were the files included in the original project? It's meant to do this just for files that weren't included in the original so that they don't automatically get included in the converted project

**Comment by superstrom** [comment]
I've seen this happen if you run migrate on an already VS2017-style project.

**Comment by josh-degraw** [comment]
@mungojam No they weren't explicitly referenced in the project, and @superstrom I think that might have been the case. Is there any sort of fix that can be done for that? I had manually updated a few of the projects, and I was hoping to clean up some elements that were still left over from that in the process.

**Comment by mungojam** [comment]
What command did you run to do the conversion and did you use the wizard? I thought it blocked conversions for VS2017 projects and made you run modernise instead

If you're able to share an example that would be really helpful

@andrew-boyarshin

**Comment by superstrom** [comment]
I can reproduce with
```
dotnet new console
dotnet migrate-2017 wizard
```

**Comment by josh-degraw** [comment]
@superstrom Yep, that's basically how it happened for me, and the output looks just like that.

**Comment by hvanbakel** [comment]
Yeah I think I can see how this happens:
migrate looks for all the files in the csproj
there are none, so all the files on disk must be excluded from the project thus insert all those removes 😄 

I guess we can fix that, yes.

**Comment by hvanbakel** [comment]
Would you mind trying with:
https://www.nuget.org/packages/Project2015To2017.Migrate2017.Tool/4.1.0-beta.3

It does seem to work for me given the repro case above.

**Comment by superstrom** [comment]
Yeah, the update is working for me.
