### ISSUE TITLE
Can sqlproj files be converted to sdk style too?

### ISSUE THREAD

**Issue by bytefluxio** [hvanbakel/CsprojToVs2017#271]
I am aware that the wizard currently does not convert sqlproj files to the sdk style.

I'm currently tasked with converting the csproj files of a few internal tools we have to the new sdk style and as a first step am using the migration wizard, before doing more changes/fixes by hand.

I now encountered a sqlproj file and was wondering if in theory this could be converted aswell. My google-fu doesn't seem advanced enough to find the answer, so I was wondering if anyone here might have more knowledge and insight on the matter.

**Comment by bytefluxio** [comment]
For anyone else wondering: While the tool didn't help in the conversion, I was able to convert it by hand.

**Comment by brettpostin** [comment]
@bytefluxio do you have guidance or resources that helped you do this? We have a large sqlproj file that we would like to upgrade but didn't think it was possible!
