### ISSUE TITLE
Question about "It will simplify porting to other runtimes and enable possible .NET SDK tooling improvements"

### ISSUE THREAD

**Issue by laurentkempe** [hvanbakel/CsprojToVs2017#277]
First I would like to thank you for the fantastic work you have done on this tool which I guess saves lots of time to lots of people 👍

I've got several messages like the following one 

> A better way to reference 'Microsoft.CSharp' assembly is using respective 'Microsoft.CSharp' NuGet package. It will simplify porting to other runtimes and enable possible .NET SDK tooling improvements.

I am not sure to understand why there is some advantages, could explain me or point me to some documentation which I couldn't find?

Thanks!

**Comment by laurentkempe** [comment]
Forget about my question it is clear now!

**Comment by kevinpohlmeier** [comment]
I came across this too. This seems to happen when you have a direct reference to an assembly in your project, but there is a nuget version available.
