### ISSUE TITLE
Use shorter way of switching of GenerateAssemblyInfo

### ISSUE THREAD

**Issue by kmorcinek** [hvanbakel/CsprojToVs2017#29]
Right now after conversion is have:

` <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
    <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>`

and if can be simplified to just:
`<GenerateAssemblyInfo>false</GenerateAssemblyInfo>`

Should I create PR with this change?

**Comment by hvanbakel** [comment]
This shouldn't be to hard, if you want you can create a PR. If not I'll address it sometime in the near future.
