### ISSUE TITLE
ItemGroup with <Reference>'s should be deleted

### ISSUE THREAD

**Issue by kmorcinek** [hvanbakel/CsprojToVs2017#30]
I am not quite sure how it works but after migration I always have to manually delete node that starts from:
`<ItemGroup>
    <Reference Include="AutoFixture, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b24654c590009d4f, processorArchitecture=MSIL">
      <HintPath>..\..\packages\AutoFixture.4.0.0-rc1\lib\net452\AutoFixture.dll</HintPath>
    </Reference>`

Can it be removed?

**Comment by hvanbakel** [comment]
Do you have an example csproj to begin with?

**Comment by kmorcinek** [comment]
Thanks, tested version 1.3.1 and works. Great tool :)
