### ISSUE TITLE
Now that the code has been migrated to .NET 6.0, can we have a new version published please?

### ISSUE THREAD

**Issue by andrewimcclement** [hvanbakel/CsprojToVs2017#307]
Version 4.1.3 (current latest version of Project2015To2017.Migrate2019.Tool etc.) uses .NET Core 2.1, which is out of support.  https://github.com/hvanbakel/CsprojToVs2017/commit/4037bebe5c4feee2e8c0bedcd0d22c9d83400c15 migrated the code to use .NET 6.0, which is the current LTS version of .NET.  It would be great to have a new version published so we can run the tool without needing to install .NET Core 2.1.

Since this would now require .NET 6.0 instead of .NET Core 2.1, I would suggest that this requires a major version update (i.e. becomes version 5.0.0).

**Comment by devlead** [comment]
@hvanbakel first of all thanks for a great tool, it's really helpful for legacy projects, especially when you need to keep them on legacy frameworks a while longer, so you just want to change the project format.

I've used the latest bits from the master branch, and it worked well for the projects I had to upgrade recently on machines with only .NET 6 installed.

Having it on NuGet.org would be more convenient, happy to help if you need any assistance with CI or similar

**Comment by drolevar** [comment]
@dustinsoftware It seems that the owned has abandoned the project for whatever reason. Will you bother to make a fork and push it over to Nuget? If not, I could try myself.

**Comment by hvanbakel** [comment]
@drolevar reason being that this migration is now built into visual studio, so not sure if there's still a need for this. I would use the Microsoft tooling over this, the reason this was created was the lack of Microsoft tooling at the time

**Comment by gibbed** [comment]
> @drolevar reason being that this migration is now built into visual studio, so not sure if there's still a need for this. I would use the Microsoft tooling over this, the reason this was created was the lack of Microsoft tooling at the time

Does that require newer VS? Or is the Microsoft tooling now available in say, VS2019?

**Comment by andrewimcclement** [comment]
@hvanbakel My main reason for still using this is that the built-in migration tool automatically includes an upgrade to .NET 6+, whereas I usually want to do that as a separate step to avoid breaking changes (i.e. stay on .NET Framework 4.8).  This tool manages the conversion to SDK style without forcing change of target framework (and in particular, any associated transformations).  In particular, this allows piecemeal conversion of a large solution to SDK style without upgrading the target framework from .NET Framework 4.8 at the same time.

@gibbed See https://dotnet.microsoft.com/en-us/platform/upgrade-assistant or https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.upgradeassistant for the MS tooling - I've only used it in VS 2022 but I have found it works well for performing the actual upgrade from one target framework to another.

**Comment by hvanbakel** [comment]
@andrewimcclement I can check the coming week what it would take to push this to nuget again.
I might just do that manually

**Comment by mungojam** [comment]
Worth getting this working as it is more featureful. But note that the official tooling doesn't require VS at all and also supports SDK only conversion.

We added lots more tidying up in this tool so it is better for mass conversions

**Comment by hvanbakel** [comment]
There's a new release here
https://github.com/hvanbakel/CsprojToVs2017/releases/tag/untagged-340dc5f0fcb6eab8f193

So the only thing left is revving the package version so that the nuget packages republish. Correct?

If so can someone generate a PR for that by updating the version here?
https://github.com/hvanbakel/CsprojToVs2017/blob/29a0e55ff105e73f28524009691eb75ae3ab5de5/Directory.Build.props#L13C10-L13C10

Then we'll merge that and close this issue, correct?

**Comment by mungojam** [comment]
#311 created for updating the version

**Comment by hvanbakel** [comment]
New version has been published I think that'll do it for this. If not, let me know

**Comment by andrewimcclement** [comment]
Tyvm @hvanbakel
