### ISSUE TITLE
Add AppVeyor for automatic release on tag?

### ISSUE THREAD

**Issue by casz** [hvanbakel/CsprojToVs2017#35]
As #33 is yet to be released perhaps would be good to look at some CI option as well as automatic release should be possible with [AppVeyor](https://www.appveyor.com/)

**Comment by hvanbakel** [comment]
So I have a build setup on AppVeyor but never setup anything other than that, let me have a look at that.

**Comment by casz** [comment]
I'll be happy to help with an [appveyor.yml file](https://www.appveyor.com/docs/appveyor-yml/) 👍

**Comment by hvanbakel** [comment]
That would be great, can you write up an example that would get me started?

**Comment by casz** [comment]
Sure thing, I'll try and have something later today, if not at least on the weekend 😄

**Comment by hvanbakel** [comment]
I consider this closed see https://github.com/hvanbakel/CsprojToVs2017/releases/tag/CSProj2015To2017-v1.5.102

now every checkin will be automatically released without doing a thing!

**Comment by casz** [comment]
@hvanbakel thanks for being awesome 👍

**Comment by casz** [comment]
@hvanbakel The AppVeyor stuff seems to have paid off :) Love where the project is heading.
