### ISSUE TITLE
Transitive NuGet dependencies should be omitted

### ISSUE THREAD

**Issue by lukas-lansky** [hvanbakel/CsprojToVs2017#38]
The new csproj format does not require to include dependencies of project dependencies. That makes clear what is needed for the project to function -- and it obviously makes the resulting list much shorter. Tool should check which dependencies are transitive and omit them from the generated csproj.

I can offer the code under MIT/Apache/... . What license do you use?

**Comment by hvanbakel** [comment]
We've talked about this in #28. I have to say (given that this came up again) maybe I can put in a config switch to toggle that off. I would like to keep the tool fast though. 

Do you have this code already written up?

I don't think I put a license on this project yet, I need to look into that again (been a while).

**Comment by lukas-lansky** [comment]
Oh, sorry, didn't notice that conversation. I've just started, so if you think this should be handled separately of this conversion tool, you can close the ticket and I can just put the code into some Gist as csx.

**Comment by hvanbakel** [comment]
no worries, I think it makes sense for this tool to become obsolete, the simplifying of the references can be ran over and over again and is not specific to the move to 2017.

If you write it up though, please let me know. I would be very interested! I can put a link here to that tool so we 'solve' that problem too :).
