### ISSUE TITLE
packages.config should be deleted

### ISSUE THREAD

**Issue by mbp** [hvanbakel/CsprojToVs2017#5]
After converting project, `packages.config` still remains even though those references are now migrated to `<PackageReference>` elements.

The file is also specifically mentioned in the generated `csproj`:

    <None Include="packages.config" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" />

Which it should not.

I recommend this file is deleted. Or at least renamed to `.old`.

**Comment by mbp** [comment]
The same probably applies for any nuspec file being converted to be inside `csproj`

**Comment by hvanbakel** [comment]
Agreed, but we still need to figure out if we have parity for both files in the new system.

At first I didn't want to touch any of these files but it is weird to keep them included. I think renaming them too is worthwhile and safe.

**Comment by hvanbakel** [comment]
This is now renamed by merging #26 the packages config is now renamed.
I won't delete any file as I cannot assume version control being present.
