### ISSUE TITLE
File inclusion checks get confused when only character case is different

### ISSUE THREAD

**Issue by mungojam** [hvanbakel/CsprojToVs2017#55]
When the case has changed between the original project and the included files, the converter gets confused as it is presumably doing a case sensitive check. Not sure how my projects ended up with different cases but they did.

Here's a simple sample I created and the messages generated

[DemoApp.zip](https://github.com/hvanbakel/CsprojToVs2017/files/1704736/DemoApp.zip)

```
File found which was not included, consider removing ####\DemoApp\program.cs.

File was included but is not on disk: ####\DemoApp\Program.cs.
```

**Comment by hvanbakel** [comment]
Great repro inside the zip file, made verification of the fix super easy, thanks!
