### ISSUE TITLE
TFS TFVC .vspscc files are not being excluded from resultant project

### ISSUE THREAD

**Issue by mungojam** [hvanbakel/CsprojToVs2017#59]
Visual Studio uses vspscc files to keep track of which projects are in TFS (I think that's how it works anyway). In old style projects, these don't get automatically included in projects, so we aren't used to having them there.

When converting, they are then included so I end up explicitly excluding them in the new project file.

I can't decide whether you should add in this exclusion automatically. I have doubts because when I create a new .net standard project in VS, it doesn't exclude these files.

Hopefully we will move to Git soon anyway and not have to worry about it. Until then though, I would quite like to keep them hidden.

Same example project as in #58: [ClassLibrary1.zip](https://github.com/hvanbakel/CsprojToVs2017/files/1796078/ClassLibrary1.zip)

**Comment by hvanbakel** [comment]
I believe the best approach is to do what VS does for a new project, I’ve seen them being included there so I wasn’t bothered by having them show up after converting a project. Or we can add a command line switch.

**Comment by mungojam** [comment]
yeah, that's fair enough. This one isn't a big deal for me and we plan to move to Git later this year anyway so I'll be able to get rid of the blighters then anyway! That will actually be easier to do without the excludes. You can see I'm indecisive on this one :)

Happy to close unless you want to add the command line switch

**Comment by hvanbakel** [comment]
I'm not going to add this since VS seems to add them anyway so there might be a reasoning which I don't know about, so better safe then sorry :).

**Comment by mungojam** [comment]
Totally understand, thanks
