### ISSUE TITLE
Create single backup folder of all potentially affected files rather than renaming

### ISSUE THREAD

**Issue by mungojam** [hvanbakel/CsprojToVs2017#60]
Creating a single backup zip would make it possible to support deleting files such as packages.config and AssemblyInfo.cs and would be simpler to clear up once finished.

Alternatively make a copy of the whole folder like VS does (or did) when upgrading to a later version.

**Comment by hvanbakel** [comment]
I can see all of this happening, would be behind a command line switch but how would you know that it is safe to delete assemblyinfo.cs? There's a lot of other assembly level attributes like `InternalsVisibleTo` etcetera that would still need a place in the project.

**Comment by mungojam** [comment]
I would only delete it if all existing properties in it were accounted for. In our case we rarely use `InternalsVisibleTo` so that particular one wouldn't affect us. There are other cases you wouldn't be able to deal with too like 1.0.* style versioning.

I think rather than command line switching, you could switch this to be a nuget package that took additional Func<>'s or something for pre and post-processing. For example in our case, I know how we will deal with 1.0.* style versioning which is fairly bespoke, so I could add a pre-conversion step to remove it from the AssemblyInfo and a post-conversion step to add the appropriate props to the converted project file.

**Comment by hvanbakel** [comment]
If you're saying that it would be helpful to extract the actual conversion logic from the console project itself, I can do that and publish that as a nuget package.

About dealing with the 1.0.* style versioning, do you have a link on that? I've not been able to find anything on that yet.

**Comment by mungojam** [comment]
#67 added for creating a package, yes please :)

Versioning in the new sdk projects can use these properties:

```xml
    <Version>1.0.7777.0</Version>
    <AssemblyVersion>1.0.8888.0</AssemblyVersion>
    <FileVersion>1.0.9999.0</FileVersion>
```

This is equivalent to:
```C#
[assembly: AssemblyInformationalVersion("1.0.7777")]
[assembly: AssemblyVersion("1.0.8888")]
[assembly: AssemblyFileVersion("1.0.9999")]
```

I can't remember if you already do that conversion for non 1.0.* style versions, but it would be useful to.

As for 1.0.* style versions, these are no longer supported, so everybody is having to roll their own somewhat. It will often be dependent on build servers or things like that and people's versioning strategies will vary so I don't think you can realistically cater for it. That's where supporting pre and post-processing functions would work well.

Here's one of a few threads with different ideas on how people solve it, but again I wouldn't expect any of these to be embedded in your tool:
https://stackoverflow.com/questions/43019832/auto-versioning-in-visual-studio-2017-net-core

**Comment by hvanbakel** [comment]
Given that the package now exists, I assume you'll build this one on top of the package, so we can close this one?

**Comment by mungojam** [comment]
Can do but I would still prefer it as part of the tool or make backups optional. Otherwise to clear up I have to look for individual backup files. 

The VS project upgrader normally makes a backup folder of the whole project which would be fine too.
