### ISSUE TITLE
Imports fail

### ISSUE THREAD

**Issue by remcoongit** [hvanbakel/CsprojToVs2017#62]
`<Import Project="..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.8\build\net45\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props" Condition="Exists('..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.8\build\net45\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props')" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" />`

 error  : The attribute "xmlns" in element <Import> is unrecognized.

**Comment by hvanbakel** [comment]
Is this on the latest version? I cannot reproduce this. If I add this line
```
  <Import Project="..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.8\build\net45\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props" Condition="Exists('..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.8\build\net45\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props')" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" />
```
to the old csproj, it works fine and gets transformed into
```
  <Import Project="..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.8\build\net45\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props" Condition="Exists('..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.8\build\net45\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props')" />
```
without an xmlns attribute

**Comment by hvanbakel** [comment]
I just saw what you're reporting, that is however BEFORE conversion. Can you confirm?

**Comment by remcoongit** [comment]
Hi,  this is after the tool ran over the old project files. It did not convert it. Ill see if I can get you more details on this project file on monday.

**Comment by hvanbakel** [comment]
Please let me know when you have more info.
