### ISSUE TITLE
Change solution GUIDs to explicitly specify to open with the new project format

### ISSUE THREAD

**Issue by mungojam** [hvanbakel/CsprojToVs2017#68]
A very minor one, especially as VS maybe fixes it automatically on first open

The GUIDs in the solution file tell VS what type of project loader to use. If we leave it as is, then VS uses some heuristics to figure out that it should actually open with the new SDK-style format loader rather than the legacy one. This can lead to issues as described: https://github.com/dotnet/project-system/issues/1358

The best approach would be to change the GUIDs in the solution file to: 
9A19103F-16F7-4668-BE54-9A1E7A4F7556

which is the GUID of the new loader. VS then uses the new project loader regardless and presumably opens the projects a bit quicker.

Full details on VS behaviour:
https://github.com/dotnet/project-system/blob/master/docs/opening-with-cps.md

**Comment by hvanbakel** [comment]
I'm not touching the solution file :) especially not if there's small gain which VS might fix itself as I'm not aware of what the consequences are.
