### ISSUE TITLE
PostBuildEvent is not migrated

### ISSUE THREAD

**Issue by knoxi** [hvanbakel/CsprojToVs2017#70]
We have some pre-build and post build events in some old projects.
These events are not migrated to new PostBuild target elements.

**Comment by hvanbakel** [comment]
Are these post build events that were manually put into the project? If they are coming from packages they would no longer live inside of the csproj.

**Comment by knoxi** [comment]
I mean the pre-build and post-build events from the project build events.

Here the configuration before migration:
![project_build_events_before_migrate](https://user-images.githubusercontent.com/5229316/38235309-35d17192-3710-11e8-9998-75e823452d07.png)

Here the configuration after migration:
![project_build_events_after_migrate](https://user-images.githubusercontent.com/5229316/38235326-4044f914-3710-11e8-9165-295b25fc1510.png)

I attach the sample solution in #71
