### ISSUE TITLE
Custom configurations are not available after migration

### ISSUE THREAD

**Issue by knoxi** [hvanbakel/CsprojToVs2017#71]
After migration, our custom configurations are no longer available in the project properties.
The configurations are still in the project files.
After adding the line `<Configurations>Debug;Release;Release_CI</Configurations>` in the first PropertyGroup in the project file, we got our custom configuration back.

**Comment by hvanbakel** [comment]
Can you share an example?

I think what you mean is that you have this?
```
  <PropertyGroup>
    <Configuration>Debug;OtherConfiguration</Configuration>
  </PropertyGroup>
```
Is that correct?

**Comment by knoxi** [comment]
Exactly. 

All configurations remains in the project in the PropertyGroups but are not shown after upgrade.
`  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
...`

Before migration:
![project_configurations_before_migrate](https://user-images.githubusercontent.com/5229316/38235791-e09f140c-3711-11e8-87eb-9d2bb7165f5f.png)

After migration:
![project_configurations_after_migrate](https://user-images.githubusercontent.com/5229316/38235803-e938bfaa-3711-11e8-89e4-bdc78293c1db.png)


After inserting manually the config they reappear:
`  <PropertyGroup>
    <Configuration**s**>Debug;Release;Release_CI</Configuration**s**>
  </PropertyGroup>
`

**Comment by hvanbakel** [comment]
Your examples were really valuable. Both issues you filed are fixed and should be in:
https://github.com/hvanbakel/CsprojToVs2017/releases/tag/1.5.12
