### ISSUE TITLE
Vbproj support?

### ISSUE THREAD

**Issue by hheexx** [hvanbakel/CsprojToVs2017#74]
Do you plan to support vb projects?
There should not be a lot of difference I guess..

**Comment by hvanbakel** [comment]
Can you send me a couple of example vbproj files? I don't think there's a
big difference no it's just that I never work with it so I don't have a
good set of test projects.

**Comment by hvanbakel** [comment]
Can you check:
https://github.com/hvanbakel/CsprojToVs2017/releases/tag/1.5.12-beta

let me know what you find.

**Comment by hheexx** [comment]
Unhandled Exception: System.IO.IOException: The directory name is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
   at Project2015To2017.ProjectConverter.<Convert>d__1.MoveNext()
   at Project2015To2017.Console.Program.Main(String[] args)

**Comment by hvanbakel** [comment]
Can you try with an individual project file first? I assume this was with
either a folder or a solution.

**Comment by hheexx** [comment]
No, I tried loading a project.

**Comment by mungojam** [comment]
I think it's the first switcher in ProjectConvertor. It could do with changing to test if the provided path is a file and then check against a list of allowed types. The error messages can then be better if somebody did actually pass in an unsupported file type.

**Comment by hvanbakel** [comment]
There's a new release here:
https://github.com/hvanbakel/CsprojToVs2017/releases/tag/1.5.12-beta01
If you get an exception, could you include the entire console output?

**Comment by andrew-boyarshin** [comment]
@hvanbakel why not merge VBProj-support branch into master, despite not thoroughly done testing? It will not affect the main purpose (csproj) but will simplify possible future work on vbproj & fsproj.

**Comment by andrew-boyarshin** [comment]
@hvanbakel bump the issue. Probably won't hurt to add rebased changes to the new master.
