### ISSUE TITLE
Feauture Request: Add parameter to allow .net framework version upgrade during convert

### ISSUE THREAD

**Issue by MagicAndre1981** [hvanbakel/CsprojToVs2017#87]
After the covert, I can't compile the CodedUI Tests, because Microsoft.TestPlatform.TestHost 15.0.0 is not compatible with .net framework 4.0

`NU1202 Package Microsoft.TestPlatform.TestHost 15.0.0 is not compatible with net40 (.NETFramework,Version=v4.0). Package Microsoft.TestPlatform.TestHost 15.0.0 supports:- net45 (.NETFramework,Version=v4.5)- netstandard1.5 (.NETStandard,Version=v1.5)`

 (already discovered here: https://github.com/hvanbakel/CsprojToVs2017/issues/44)

I later already plan to upgrade .net framework to 4.7.x in the new csproj files (which is easier with the new PackageReference Include because you don't need to deal with the file paths and .net framework entries in packages.config)  so it would be nice if your tool has a parameter to upgrade the .net framework directly during the process of converting.

**Comment by andrew-boyarshin** [comment]
@MagicAndre1981 I believe that is handled by #135.
