### ISSUE TITLE
Just flagging what was announced today around .net core 3.0

### ISSUE THREAD

**Issue by mungojam** [hvanbakel/CsprojToVs2017#97]
Looks like Microsoft will finally be providing a converter, but it may not come to preview till late this year with a release next year

> The first part of adopting .NET Core 3 for desktop projects will be migrating to SDK-style projects. There will be a migration experience in Visual Studio and available at the command line.

https://blogs.msdn.microsoft.com/dotnet/2018/05/07/net-core-3-and-support-for-windows-desktop-applications/

I plan to stick with your tool and try to get our big migration done in the next month or so. I'll keep submitting changes if that's ok. I think I've raised issues for almost everything that will give us what we need and will keep submitting PRs.

**Comment by Pilchie** [comment]
Note: It's entirely possible that will look for some existing resources when we start working on migration too :wink:

We don't currently have a migration story, we just know that we'll need to build one.

Keep those fixes coming!

**Comment by hvanbakel** [comment]
So I saw the part where you could make a tree (using transitive dependencies) from a list of dependencies. That’s really nice as we don’t have that yet. The conversion itself does a lot more though.

I talked about conversion with @terrajobst at Build last year and at that time there wasn’t a plan for migration yet. So if that happens to change then that would be awesome, but by the time that might be done most of the projects might have been converted already :).

**Comment by mungojam** [comment]
Yeah, that would kind of be funny. I expect there are plenty of Devs who will wait for something built in to VS as they won't know anything about the formats (lots of devs still don't read blogs).

I think we already have the transitive tree for all converted projects. I have used it anyway. Under Dependencies/nuget

**Comment by dvorn** [comment]
The converter is already included in 15.7: https://blog.nuget.org/20180409/migrate-packages-config-to-package-reference.html

**Comment by mungojam** [comment]
@dvorn unfortunately that converter is currently just for going from packages.config to PackageReference. The converter in this repo does that but also converts from the old project format to the new format. It also supports running from outside VS which I don't think the MS one does yet.

One nice thing the MS converter has is that it tries to detect which are transitive dependencies, something that is currently ruled out for this tool #38. I might have a look at how they did that and see if it would suit my needs, or if I can extend it as an option for this project.

**Comment by hvanbakel** [comment]
@Pilchie given where we are today, do you think it would be worthwile to wrap this into an extension to make it more easy from a VS perspective?

**Comment by hvanbakel** [comment]
Closing this one, in favor of a net core global tool #137
